name = "Winter's Tweaks"
author = "Wolfyo"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8fabc197b043c21f64a95132ab66ca00b31d534526c6777546470a10933c3a0"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
