name = "Winter's Tweaks"
author = "Wolfyo"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e82846ca79f278b54456b5d8bd7cfd25cb6460948be140399e0e9fff1d08fadf"

[versions]
fabric = "0.16.9"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
