name: Push To 1.20.4 Continuous Deployment

on:
  push:
    branches: [1.20.4]
    paths:
      - "config/**"
      - "mods/**"
      - "resourcepacks/**"
      - "index.toml"
      - "pack.toml"

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Export
        run: |
          docker run --rm -v $(pwd):/workspace dalbitresb12/packwiz modrinth export --output "winters-tweaks-1.20.4-${{ steps.version.outputs.date }}.mrpack"

      - name: Deploy to GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "1.20.4-${{ steps.version.outputs.date }}"
          github-generate-changelog: true
          github-token: ${{ secrets.GH_TOKEN }}

          name: "1.20.4-${{ steps.version.outputs.date }}"
          version: "1.20.4-${{ steps.version.outputs.date }}"
          files: "*.mrpack"
          loaders: fabric
          game-versions: "1.20.4"

      - name: Deploy to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: faNqEX4o
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: any

          name: "1.20.4-${{ steps.version.outputs.date }}"
          version: "1.20.4-${{ steps.version.outputs.date }}"
          files: "*.mrpack"
          loaders: fabric
          game-versions: "1.20.4"
          changelog: "Changelog: https://www.github.com/RWolfyo/winters-tweaks/releases/tag/${{ steps.version.outputs.date }}/"
